name: 'ecsctl'
description: 'Manage AWS Elastic Container Service (ECS)'
inputs:
  args: 
    description: 'Inform the command and args as in cli. Check for the documentation to know all commands.'
    required: true
outputs:
  response:
    description: 'Response / Output for the command executed'

runs:
  using: 'docker'
  image: 'action.Dockerfile'
  args:
    - ${{ inputs.command }}

